studentsreports/config/routes.rb
Rails.application.routes.draw do
  resources :grades
  resources :subjects
  resources :students
  
  root "pages#show", page: "index"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

studentsreports/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

studentsreports/app/models/grade.rb
class Grade < ApplicationRecord
  belongs_to :student
  belongs_to :subject
end

studentsreports/app/models/student.rb
class Student < ApplicationRecord
  has_many :grades
  def age
    ((Date.today - self.birth_date)/365).to_i
  end
  
  def to_s
    name + " " + surname 
  end
end

studentsreports/app/models/subject.rb
class Subject < ApplicationRecord
  has_many :grades
  def to_s
    name  
  end
end

studentsreports/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

studentsreports/app/controllers/grades_controller.rb
class GradesController < ApplicationController
  before_action :set_grade, only: [:show, :edit, :update, :destroy]

  # GET /grades
  # GET /grades.json
  def index
    @grades = Grade.all
  end

  # GET /grades/1
  # GET /grades/1.json
  def show
  end

  # GET /grades/new
  def new
    @grade = Grade.new
  end

  # GET /grades/1/edit
  def edit
  end

  # POST /grades
  # POST /grades.json
  def create
    @grade = Grade.new(grade_params)

    respond_to do |format|
      if @grade.save
        format.html { redirect_to @grade, notice: 'Grade was successfully created.' }
        format.json { render :show, status: :created, location: @grade }
      else
        format.html { render :new }
        format.json { render json: @grade.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /grades/1
  # PATCH/PUT /grades/1.json
  def update
    respond_to do |format|
      if @grade.update(grade_params)
        redirect_to(@book)
      #   format.html { redirect_to @grade, notice: 'Grade was successfully updated.' }
      #   format.json { render :show, status: :ok, location: @grade }
       else
        render:edit
      #   format.html { render :edit }
      #   format.json { render json: @grade.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /grades/1
  # DELETE /grades/1.json
  def destroy
    @grade.destroy
    respond_to do |format|
      format.html { redirect_to grades_url, notice: 'Grade was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_grade
      @grade = Grade.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def grade_params
      params.require(:grade).permit(:value, :date, :student_id, :subject_id)
    end
end

studentsreports/app/controllers/pages_controller.rb
class PagesController < ApplicationController
def show
    if valid_page?
        render template: "pages/#{params[:page]}"
    else 
        render template: "public/404.html", status: :not_found
    end
end

private 
def valid_page?
    File.exist?(Pathname.new(Rails.root + "app/views/pages/#{params[:page]}.html.erb"))
end
end

studentsreports/app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :set_student, only: [:show, :edit, :update, :destroy]

  # GET /students
  # GET /students.json
  def index
    @students_grid = initialize_grid(Student)
  end

  # GET /students/1
  # GET /students/1.json
  def show
    @grades_grid = initialize_grid(@student.grades)
  end

  # GET /students/new
  def new
    @student = Student.new
  end

  # GET /students/1/edit
  def edit
  end

  # POST /students
  # POST /students.json
  def create
    @student = Student.new(student_params)

    respond_to do |format|
      if @student.save
        format.html { redirect_to @student, notice: 'Student was successfully created.' }
  format.json { render :show, status: :created, location: @student }
      else
        format.html { render :new }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /students/1
  # PATCH/PUT /students/1.json
  def update
    respond_to do |format|
      if @student.update(student_params)
        format.html { redirect_to @student, notice: 'Student was successfully updated.' }
        format.json { render :show, status: :ok, location: @student }
      else
        format.html { render :edit }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /students/1
  # DELETE /students/1.json
  def destroy
    @student.destroy
    respond_to do |format|
      format.html { redirect_to students_url, notice: 'Student was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_student
      @student = Student.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def student_params
      params.require(:student).permit(:name, :surname, :birth_date)
    end
end

studentsreports/app/controllers/subjects_controller.rb
class SubjectsController < ApplicationController
  before_action :set_subject, only: [:show, :edit, :update, :destroy]

  # GET /subjects
  # GET /subjects.json
  def index
    @subjects = Subject.all
  end

  # GET /subjects/1
  # GET /subjects/1.json
  def show
  end

  # GET /subjects/new
  def new
    @subject = Subject.new
  end

  # GET /subjects/1/edit
  def edit
  end

  # POST /subjects
  # POST /subjects.json
  def create
    @subject = Subject.new(subject_params)

    respond_to do |format|
      if @subject.save
        format.html { redirect_to @subject, notice: 'Subject was successfully created.' }
        format.json { render :show, status: :created, location: @subject }
      else
        format.html { render :new }
        format.json { render json: @subject.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /subjects/1
  # PATCH/PUT /subjects/1.json
  def update
    respond_to do |format|
      if @subject.update(subject_params)
        format.html { redirect_to @subject, notice: 'Subject was successfully updated.' }
        format.json { render :show, status: :ok, location: @subject }
      else
        format.html { render :edit }
        format.json { render json: @subject.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /subjects/1
  # DELETE /subjects/1.json
  def destroy
    @subject.destroy
    respond_to do |format|
      format.html { redirect_to subjects_url, notice: 'Subject was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_subject
      @subject = Subject.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def subject_params
      params.require(:subject).permit(:name)
    end
end

studentsreports/app/helpers/application_helper.rb
module ApplicationHelper
end

studentsreports/app/helpers/grades_helper.rb
module GradesHelper
end

studentsreports/app/helpers/students_helper.rb
module StudentsHelper
end

studentsreports/app/helpers/subjects_helper.rb
module SubjectsHelper
end

studentsreports/app/views/grades/_form.html.erb
<%= form_with(model: grade, local: true) do |form| %>
  <div class="form-group>
  <% if grade.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(grade.errors.count, "error") %> prohibited this grade from being saved:</h2>

      <ul>
      <% grade.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= form.label :value %>
    <%= form.number_field :value, id: :grade_value, class: "form-control"%>
  </div>

  <div class="field form-group">
    <%= form.label :date %>
    <%= form.date_select :date, class: "form-control" %>
  </div>
  <div class="field form-group">
    <%= form.label :student_id %>
    <%= form.select :student_id, Student.all.collect{|s|[s.name + " "+s.surname, s.id]}, class: "form-control"%>
  </div>


   <div class="field form-group">
     <%= form.label :subject_id %>
     <%= form.select :subject_id, Subject.all.collect{|s|[s.name, s.id]}, class: "form-control" %> 
   </div>
  <div class="actions">
    <%= form.submit class: 'btn btn-success' %>
  </div>
  <%= link_to 'Back', grades_path %>
  </div>
<% end %>

studentsreports/app/views/grades/edit.html.erb
<nav class="navbar navbar-expand-sm bg-dark navbar-dark">
    <%= link_to 'Student Card',root_path %>
<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
  <span class="navbar-toggler-icon"></span>
</button>
</nav>

<div class="container">
<h1>Editing Grade</h1>

    <%= render 'form', grade: @grade %>

    <%= link_to 'Show', @grade %> |
</div>

studentsreports/app/views/grades/index.html.erb
<nav class="navbar navbar-expand-sm bg-dark navbar-dark">
<%= link_to 'Student Card',root_path %>
<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
  <span class="navbar-toggler-icon"></span>
</button>
<div class="collapse navbar-collapse" id="collapsibleNavbar">
</div>
</nav>

<p id="notice"><%= notice %></p>

<h1>Grades</h1>
<div class='container-fluid col-10'>
<div class="table-responsive">
<table class="table">
  <thead>
    <tr>
      <th>Value</th>
      <th>Date</th>
      <th>Student</th>
      <th>Subject</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @grades.each do |grade| %>
      <tr>
        <td><%= grade.value %></td>
        <td><%= grade.date %></td>
        <td><%= grade.student.to_s %></td>
        <td><%= grade.subject.to_s %></td>
        <td><%= link_to 'Show', grade %></td>
        <td><%= link_to 'Edit', edit_grade_path(grade) %></td>
        <td><%= link_to 'Destroy', grade, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Grade', new_grade_path ,class: 'btn btn-info' %>
</div>
</div>

studentsreports/app/views/grades/new.html.erb
<nav class="navbar navbar-expand-sm bg-dark navbar-dark">

<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
  <span class="navbar-toggler-icon"></span>
</button>
<div class="collapse navbar-collapse" id="collapsibleNavbar">
</div>
</nav>


<h1>New Grade</h1>

<%= render 'form', grade: @grade %>

studentsreports/app/views/grades/show.html.erb
<nav class="navbar navbar-expand-sm bg-dark navbar-dark">
<%= link_to 'Student Card',root_path %>
<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
  <span class="navbar-toggler-icon"></span>
</button>
<div class="collapse navbar-collapse" id="collapsibleNavbar">
</div>
</nav>

<div class="table-responsive">
<table class="table">
  <thead>
    <tr>
      <th scope="col"><strong>Value:</strong></th>
      <th scope="col"><strong>Date:</strong></th>
      <th scope="col"><strong>Student:</strong></th>
      <th scope="col"><strong>Subject:</strong></th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><%= @grade.value %></td>
      <td> <%= @grade.date %></td>
      <td><%= @grade.student %></td>
      <td><%= @grade.subject %></td>
      <td><%= link_to 'Edit', edit_grade_path(@grade) %></td>
    </tr>
  </tbody>
  </table>
  </div>

studentsreports/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>StudentReports</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

studentsreports/app/views/pages/index.html.erb
<nav class="navbar navbar-expand-sm bg-dark navbar-dark">
    <a class="navbar-brand" href="#">Students Card</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="collapsibleNavbar">

            <ul class="navbar-nav">
                    <li class="nav-item">
                      <%= link_to 'Students', students_path%>
                    </li>
                    <li class="nav-item">
                      <%= link_to 'Grades', grades_path %>
                    </li>
                    <li class="nav-item">
                      <%= link_to 'Subjects', subjects_path%>
                    </li>    
                  </ul>
                </div>  
              </nav>
              <div class="container">

              </div>

studentsreports/app/views/students/_form.html.erb
<%= form_with(model: student, local: true) do |form| %>
   <div class="form-group>
  <% if student.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(student.errors.count, "error") %> prohibited this student from being saved:</h2>

      <ul>
      <% student.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= form.label :name%>
    <%= form.text_field :name, id: :student_name,class: 'form-control'%>
  </div>

  <div class="field form-group">
    <%= form.label :surname %>
    <%= form.text_field :surname, id: :student_surname, class: 'form-control'%>
  </div>

  <div class="field form-group">
    <%= form.label :birth_date %>
    <%= form.date_select :birth_date, id: :student_birth_date, class: 'form-control' %>
  </div>

  <div class="actions btn btn-default">
    <%= form.submit class: 'btn btn-success'%>
  </div>
  <%= link_to 'Back', students_path, style: 'float:right;', class: 'btn btn-info' %>
</div>
<% end %>

studentsreports/app/views/students/_student_grades.html.erb
<%=
grid(@grades_grid) do |g|
    g.column attribute: "value", name: "Value"
    g.column attribute: "name", name: "Subject", assoc: :subject
end 
%>

studentsreports/app/views/students/edit.html.erb
<h1>Editing Student</h1>

<%= render 'form', student: @student %>

<%= link_to 'Show', @student %> |
<%= link_to 'Back', students_path %>

studentsreports/app/views/students/index.html.erb
<nav class="navbar navbar-expand-sm bg-dark navbar-dark">
    <%= link_to 'Student Card',root_path %>
<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
  <span class="navbar-toggler-icon"></span>
</button>
<div class="collapse navbar-collapse" id="collapsibleNavbar">
  <ul class="nav navbar-nav navbar-right">
    <li> 
    <%= link_to 'New Student', new_student_path %>
    </li>
    <li> 
        <%= link_to 'Grades', grades_path %>
    </li>
    <li> 
        <%= link_to 'Subjects', subjects_path %>
    </li>
  </ul>
</div>
</nav>

<p id="notice"><%= notice %></p>
<div class="container-fluid">
<h1>Students:</h1>

<div class="container">
<%= grid(@students_grid) do |g|

  g.column attribute: "id", name: "ID"

  g.column attribute: "name", name: "Jmeno"

  g.column attribute: "surname", name: "Prijmeni"

  g.column do |student|
    student.age
  end

  g.column do |task|
    link_to('Edit', edit_student_path(task))
  end
end -%>
</div>
</div>

studentsreports/app/views/students/new.html.erb
<nav class="navbar navbar-expand-sm bg-dark navbar-dark">
<%= link_to 'Student Card', root_path %>
<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
  <span class="navbar-toggler-icon"></span>
</button>
<div class="collapse navbar-collapse" id="collapsibleNavbar">
</div>
</nav>

<div class="container-fluid col-8 ">
<h1>New Student</h1>
<%= render 'form', student: @student %>

</div>

studentsreports/app/views/students/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @student.name %>
</p>

<p>
  <strong>Surname:</strong>
  <%= @student.surname %>
</p>

<p>
  <strong>Birth date:</strong>
  <%= @student.birth_date %>
</p>
<%= render 'student_grade', student: @student %>

<%= link_to 'Edit', edit_student_path(@student) %> |
<%= link_to 'Back', students_path %>

studentsreports/app/views/subjects/_form.html.erb
<%= form_with(model: subject, local: true) do |form| %>
  <% if subject.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(subject.errors.count, "error") %> prohibited this subject from being saved:</h2>

      <ul>
      <% subject.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :subject_name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

studentsreports/app/views/subjects/edit.html.erb
<h1>Editing Subject</h1>

<%= render 'form', subject: @subject %>

<%= link_to 'Show', @subject %> |
<%= link_to 'Back', subjects_path %>

studentsreports/app/views/subjects/index.html.erb
<nav class="navbar navbar-expand-sm bg-dark navbar-dark">
<%= link_to 'Student Card', root_path %>
<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
  <span class="navbar-toggler-icon"></span>
</button>
<div class="collapse navbar-collapse" id="collapsibleNavbar">
</div>
</nav>

<p id="notice"><%= notice %></p>

<h1>Subjects</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @subjects.each do |subject| %>
      <tr>
        <td><%= subject.name %></td>
        <td><%= link_to 'Show', subject %></td>
        <td><%= link_to 'Edit', edit_subject_path(subject) %></td>
        <td><%= link_to 'Destroy', subject, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Subject', new_subject_path %>

studentsreports/app/views/subjects/new.html.erb
<h1>New Subject</h1>

<%= render 'form', subject: @subject %>

<%= link_to 'Back', subjects_path %>

studentsreports/app/views/subjects/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @subject.name %>
</p>

<%= link_to 'Edit', edit_subject_path(@subject) %> |
<%= link_to 'Back', subjects_path %>